### ISSUE TITLE
KeyError: 'backups'

### ISSUE THREAD

**Issue by ericmigi** [YuriCosta/WhatsApp-GD-Extractor-Multithread#46]
```
  File "/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 260, in <module>
    main(sys.argv)
  File "/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 220, in main
    for backup in backups:
  File "/WhatsApp-GD-Extractor-Multithread/WhatsAppGDExtract.py", line 105, in list_path
    for item in page[last_component]:
KeyError: 'backups'
```

Just trying this out, any idea how to fix this?

**Comment by nicolaslazo** [comment]
I've been having the same issue, it seems like the API call returns a 200 OK status but the text content is an empty dict. Maybe the API's changed? I don't know if this tool works for anyone.

One possible pointer is [this blog I found](https://sudneela.github.io/posts/the-workings-of-whatsapps-end-to-end-encrypted-backups/#--analysis---restoring) where instead of passing the auth token through the headers there's some sort of proprietary encryption being done in `ENC`. I have no extra phone numbers to mess with this but maybe someone else does? I don't want to risk losing the only copy of the data I have on GDrive
